### ISSUE TITLE
Lesson 6: ValueError: execution reverted: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by etsea117** [smartcontractkit/full-blockchain-solidity-course-py#541]
I am getting this error when attempting to run 
`brownie run scripts/fund_and_withdraw.py --network ganache-local`

Here is my fund_and_withdraw.py file:
```Python
from brownie import FundMe
from scripts.helpful_scripts import get_account


def fund():
    fund_me = FundMe[-1]
    account = get_account()
    entrance_fee = fund_me.getEntranceFee()
    print(entrance_fee)


def main():
    fund()
```
Here is my deploy.py file:
```PYthon
from brownie import FundMe, MockV3Aggregator, network, config
from scripts.helpful_scripts import (
    deploy_mocks,
    get_account,
    LOCAL_BLOCKCHAIN_ENVIRONMENTS,
)
from web3 import Web3


def deploy_fund_me():
    account = get_account()
    # pass the price feed address to our fundme address

    # if we are on a persistent network like rinkeby, use the associated address
    # otherwise, deploy mocks
    if network.show_active() not in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        price_feed_address = config["networks"][network.show_active()][
            "eth_usd_price_feed"
        ]
    else:
        deploy_mocks()
        price_feed_address = MockV3Aggregator[-1].address

    fund_me = FundMe.deploy(
        "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e",
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify"),
    )
    print(f"Contract deployed to {fund_me.address}")


def main():
    deploy_fund_me()
```
Here is my helpful_scripts.py file:
```Python
from brownie import network, config, accounts, MockV3Aggregator
from web3 import Web3

LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local"]

DECIMALS = 8
STARTING_PRICE = 200000000000


def get_account():
    if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])


def deploy_mocks():
    print(f"The active network is {network.show_active()}")
    print("Deploying Mocks...")
    if len(MockV3Aggregator) <= 0:
        MockV3Aggregator.deploy(DECIMALS, STARTING_PRICE, {"from": get_account()})
    print("Mocks Deployed!")
```
Here is my FundMe.sol file:
```Solidity
// SPDX-License-Identifier: MIT

pragma solidity >=0.6.6 <0.9.0;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";

contract FundMe {
    using SafeMathChainlink for uint256;

    mapping(address => uint256) public addressToAmountFunded;
    address[] public funders;
    address public owner;
    AggregatorV3Interface public priceFeed;

    constructor(address _priceFeed) public {
        priceFeed = AggregatorV3Interface(_priceFeed);
        owner = msg.sender;
    }

    function fund() public payable {
        uint256 minimumUSD = 50 * 10**18;
        require(
            getConversionRate(msg.value) >= minimumUSD,
            "You need to spend more ETH!"
        );
        addressToAmountFunded[msg.sender] += msg.value;
        funders.push(msg.sender);
    }

    function getVersion() public view returns (uint256) {
        return priceFeed.version();
    }

    function getPrice() public view returns (uint256) {
        (, int256 answer, , , ) = priceFeed.latestRoundData();
        return uint256(answer * 10000000000);
    }

    // 1000000000
    function getConversionRate(uint256 ethAmount)
        public
        view
        returns (uint256)
    {
        uint256 ethPrice = getPrice();
        uint256 ethAmountInUsd = (ethPrice * ethAmount) / 1000000000000000000;
        return ethAmountInUsd;
    }

    function getEntranceFee() public view returns (uint256) {
        // minimumUSD
        uint256 minimumUSD = 50 * 10**18;
        uint256 price = getPrice();
        uint256 precision = 1 * 10**18;
        return (minimumUSD * precision) / price;
    }

    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }

    function withdraw() public payable onlyOwner {
        msg.sender.transfer(address(this).balance);

        for (
            uint256 funderIndex = 0;
            funderIndex < funders.length;
            funderIndex++
        ) {
            address funder = funders[funderIndex];
            addressToAmountFunded[funder] = 0;
        }
        funders = new address[](0);
    }
}
```

**Comment by etsea117** [comment]
Based on [THIS](https://ethereum.stackexchange.com/questions/114889/deploying-ganache-local-w-brownie-vm-exception-while-processing-transaction-in) ethereum.stackexchange link, it is an issue with the getPrice() function returning a value less than 1. Still not sure how to resolve it.

**Comment by cromewar** [comment]
Hello @etsea117 Thanks for sharing your code, however you said you were getting "this" error, but didn't actually share the error itself, so could you please post here a screenshot of the error?

But if I have to guess I would say the error is here: 

```Python

    fund_me = FundMe.deploy(
        "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e",
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify"),
    )
```

The address you are using for the pricefeed is for Rinkeby network, is your ganache-local configured with the same network?

**Comment by Karam99-jpg** [comment]
there not a error exactly the thing is it should return the "current price: 25000000000000000" but actually it is returning 250000, and while I try to make a transaction then it is unable to calculate the gas price, hence it says your have add more ether not meet the minimum requirements

**Comment by cromewar** [comment]
@Karam99-jpg we use the 18 digit standard as most of the ERC20 tokens works with it, but the price feed does not actually returns a value like that, so please be sure your math is correct (your are adding or multiplying correctly the values)

**Comment by Karam99-jpg** [comment]
thanks it is solved now

**Comment by karlMoreno** [comment]
Hi @Karam99-jpg I'm running into the same error but my only difference from ur code is that instead of having that address in your
```
    fund_me = FundMe.deploy(
        "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e",
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify"),
    )
```

I have 

```
 fund_me = FundMe.deploy(
        price_feed_address,
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify"),
    )
```
instead

why did you use a specific address instead of price_feed_address?

**Comment by Karam99-jpg** [comment]
> Hi @Karam99-jpg I'm running into the same error but my only difference from ur code is that instead of having that address in your
> 
> ```
>     fund_me = FundMe.deploy(
>         "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e",
>         {"from": account},
>         publish_source=config["networks"][network.show_active()].get("verify"),
>     )
> ```
> 
> I have
> 
> ```
>  fund_me = FundMe.deploy(
>         price_feed_address,
>         {"from": account},
>         publish_source=config["networks"][network.show_active()].get("verify"),
>     )
> ```
> 
> instead
> 
> why did you use a specific address instead of price_feed_address?

Because this address is for price feed on mainnet ethereum

**Comment by cromewar** [comment]
@Karam99-jpg you are awesome and 100% right that address is for mainnnet, try using the one for rinkeby @karlMoreno

**Comment by karlMoreno** [comment]
@Karam99-jpg @cromewar 
Im still getting 

```
ValueError: execution reverted: VM Exception while processing transaction: revert
```
despite just copying all of your code as my own.


and when i go to https://docs.chain.link/docs/ethereum-addresses/

The ethereum mainnet address is actually:
```
ETH / USD | 8 | 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
-- | -- | --
```

while the one you put in your contract is under the Rinkeby test net
```
ETH / USD | 8 | 0x8A753747A1Fa494EC906cE90E9f37563A8AF630e
-- | -- | --
```

**Comment by karlMoreno** [comment]
I also read and did everything in here https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/422

and still no luck. However I will note I am operating out of a docker and I am connecting to ganache-cli instead however I made sure that it is the hardfork muirGlacier version

and it runs ```brownie run scripts/deploy.py --network ganache-local``` just fine

**Comment by cromewar** [comment]
May be this be a problem related with docker? which version are you using? I'll try to reproduce the error.

**Comment by strudelPie** [comment]
I am experiencing the same error. Just adding in case any solutions?

**Comment by cromewar** [comment]
Well I installed a docker instance with the same version and I couldn't reproduce the error. @karlMoreno just as a I try, could you please clone the repo of the course from github and run it, does it works?

**Comment by karlMoreno** [comment]
@cromewar I re did the project and cloned the repo, I remade the docker and still its the same error.

**Comment by cromewar** [comment]
Sorry for the delay, this must be something related on how dockers in connecting to ganache, may be something related to the firewall. Did you tried out of a docker instance?

**Comment by mattsegura** [comment]
> @cromewar I re did the project and cloned the repo, I remade the docker and still its the same error.

not sure if you're still having this error but he updated the FundMe.sol and it was due to a rounding error
